config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'home/index'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user
      if user.authenticate(params[:session][:password])
        log_in user
        redirect_to user, notice: "Welcome to toy_app_demo"
      else
        flash.now[:error] = "Mật khẩu không đúng. Vui lòng nhập lại!"
        render 'new'
      end
    else
      flash.now[:error] = "Email mà bạn đã nhập không khớp với bất kỳ tài khoản nào trong hệ thống. Vui lòng thử lại hoặc tạo tài khoản mới bằng cách nhấn vào liên kết Sign up ở bên dưới. "
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def show
    @user = User.find(params[:id])
    # debugger
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user, notice: "Welcome to toy_app_demo"
    else
      render 'new'
    end
  end

  private
  def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def current_user
    if @current_user.nil?
      @current_user = User.find_by(id: session[:user_id])
    else
      @current_user
    end
  end

  def logged_in?
    if current_user.nil? # Nguoi dung chua dang nhap
      return false
    else # Nguoi dung da dang nhap
      return true
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%= link_to "Sign up", signup_path%>
<%= link_to "Log in", login_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyAppDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, message| %>
        <div class="alert alert-<%= key %>">
          <%= message %>
        </div>
    <% end %>

    <% if logged_in? %>
        <%= link_to "Log out", logout_path, method: :delete %>
    <% end %>
        
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>

    <% if @user.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <br />

    <%= f.label :email %>
    <%= f.email_field :email %>
    <br />

    <%= f.label :password %>
    <%= f.password_field :password %>
    <br />

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>
    <br />

    <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>